//
//  File.swift
//  
//
//  Created by Vaibhav on 04/02/21.
//

import Foundation
import UIKit

public enum UtilConstants {
    public static var screenDimension: (height: CGFloat, width: CGFloat) { return (UIScreen.main.bounds.height, UIScreen.main.bounds.width) }
    
    public static let dotMark = "• "
    public static let done = "Done"
    public static let save = "Save"
    public static let clear = "Clear"
    public static let undo = "Undo"
    public static let redo = "Redo"
    public static let delete = "Delete"
    public static let reset = "Reset"
    public static let settings = "Configure"
    public static let back = "Back"
    public static let gradient = "Gradient"
    public static let important = "Important"
    public static let oh = "Ohh ho!"
    public static let select = "Select"
    public static let great = "Great"
    public static let keepThere = "Keep there"
    public static let moveDown = "Move down"
    public static let hide = "Hide"
    public static let okay = "Okay"
    public static let shuffle = "Shuffle"
    public static let understand = "I Understand"
    public static let edit = "Edit"
    public static let folder = "Folder"
    public static let more = "More"
    public static let lockApp = "Lock App"
    public static let themes = "Themes"
    public static let note = "Note"
    public static let title = "Title"
    public static let lock = "Lock"
    public static let photo = "Photo"
    public static let album = "Album"
    public static let cancel = "Cancel"
    public static let alert = "Alert"
    public static let unlock = "Unlock"
    public static let skip = "Skip"
    public static let gotIt = "Got it!"
    public static let reminder = "Reminder"
    public static let dueDate = "Due Date"
    public static let priority = "Priority"
    public static let startDate = "Start Date"
    public static let favourite = "Important"
    public static let wallpaper = "Wallpaper"
    public static let ticker = "Ticker"
    public static let left = "Left"
    public static let never = "Never"
    public static let trashBin = "Trash Bin"
    public static let loadingPleaseWait = "Please Wait...!!"
    public static let retry = "Retry"
    public static let error = "Error"
    public static let help = "Help & How to"
    public static let Down = "Down"
    public static let pinToTop = "Pin to Top"
    public static let Unpin = "Unpin"
    public static let slideToTop = "Slide to Top"
    public static let unSlide = "Unslide"
    public static let sortBy = "Sort By"
    public static let improvemetsFeedback = "Improvement & Feedback"
    public static let blur = "Blur"
    public static let image = "Image"
    public static let presets = "Presets"
    public static let unsplash = "Unsplash"
    public static let dismiss = "Dismiss"
    public static let sounds = "Sounds"
    public static let remove = "Remove"
    public static let duplicate = "Duplicate"
    public static let saveAndExit = "Save & Exit"
    public static let exit = "Exit"
    public static let no = "No"
    public static let disappear = "Disappear"
    public static let goToSettings = "Go to Settings"
    public static let notificationFailureMessage = "To receive reminders, you must allow notifications from Settings."
    public static let trash = "Trash Bin"
    public static let today = "Today"
    public static let new = "New"
    public static let tomorrow = "Tomorrow"
    public static let prferencesNotification = "Go to Preferences -> Notifications & Focus and Allow Notifications for this App."
    public static let shareText = "Share Text"
    public static let saveAsImage = "Save as Image"
    public static let options = "Options"
    public static let readOut = "Text to Speech"
    public static let stop = "Stop"
    public static let controlCenterPersonalization = "Control Center : Personalization"
    public static let controlCenter = "Control Center"
    public static let small = "Small"
    public static let medium = "Medium"
    public static let high = "High"
    public static let urgent = "Urgent"
    public static let large = "Large"
    public static let groups = "Groups"
    public static let folders = "Folders"
    public static let sorting = "Sorting"
    public static let deletePermanently = "Delete Permanently"
    public static let tapAgainToPause = "1. Tap again 'Text to Speech' button to Stop. \n2. Device should NOT be in Silent Mode. \n3. Visit Note settings to change Voice options."
    public static let photoAccessFailureMessage = "To save Wallpapers, you must allow photo permission from Settings."
    public static let allowNotifications = "Allow Notifications!"
    public static let languageAndVoice = "Language & Voice"
    public static let add = "Add"
    public static let category = "Category"
    public static let type = "Type"
    public static let preAlarm = "Pre Alarm"
    public static let preAlarms = "Pre Alarms"
    public static let autoSnooze = "Auto Snooze"
    public static let manualSnooze = "Manual Snooze"
    public static let set = "Set"
    public static let none = "None"
    public static let specificTimes = "Fixed Times"
    public static let everyXHour = "Every few Hours"
    public static let pending = "Pending"
    public static let completed = "Completed"
    public static let modification = "Modification"
    public static let creation = "Creation"
    public static let modified = "Create"
    public static let addTime = "Add Time"
    public static let startTime = "Starting from"
    public static let moveToTrash = "Move to Trash"
    public static let repeatConstant = "Repeat"
    public static let timesADay = "Times a Day"
    public static let endTimes = "End Times"
    public static let allDay = "All Day"
    public static let allDays = "All Days"
    public static let everyDay = "Every Day"
    public static let everyWeek = "Every Week"
    public static let everyMonth = "Every Month"
    public static let everyYear = "Every Year"
    public static let days = "Days"
    public static let weeks = "Weeks"
    public static let months = "Months"
    public static let years = "Years"
    public static let drawing = "Drawing"
    public static let endDate = "End Date"
    public static let totalDays = "Total Days"
    public static let yes = "Yes"
    public static let somethingWentWrong = "Something Went Wrong"
    public static let pause = "Pause"
    public static let continue_ = "Continue"
    public static let play = "Play"
    public static let start = "Start"
    public static let recording = "Recording"
    public static let retake = "Retake"
    public static let version = "Version"
    public static let date = "Date"
    public static let custom = "Custom"
    public static let location = "Location"
    public static let appearanceMode = "Appearance Mode"
    public static let retakeRecording = "Do you want to take Fresh recording by discarding the existing one ?"
    public static let recover = "Recover"
    public static let all = "All"
    public static let _default = "Default"
    public static let light = "Light"
    public static let dark = "Dark"
    public static let isAutoSnoozeActive = "Is Auto Snooze Active"
    public static let inActive = "Inactive"
    public static let list = "List"
    public static let bullet = "Bullet"
    public static let recentlyCreated = "Recently Created"
    public static let orderBy = "Order By"
    public static let quotes = "Quotes"
    public static let library = "Library"
    public static let internetIssueTryAgain = "Please Check your internet connection and Try Again"
    public static let somethingWentWrongTryAgain = "Something went wrong, Please Try again"
    public static let firstLetterUpperCase = "First letter Upper Case"
    public static let completedTasksWhatHappen = "What should happen to Completed Tasks ?"
    public static let locationPermissionRequired = "Location permissions required"
    public static let allowLocationPermission = "Please go to settings and allow location permissions"
    public static let whatIsThis = "What is this ?"
    public static let startDateSmallerThanEndDate = "Start date must be smaller than End date"
    public static let lastDayOfMonth = "Last Day of Month"
    public static let share = "Share"
    
    
    public enum Spacing {
        public static let outerPadding:CGFloat = UIDevice.current.userInterfaceIdiom == .phone ? 16 : 18
        public static let intermittentPadding:CGFloat = UIDevice.current.userInterfaceIdiom == .phone ? 3 : 6
        public static let intrimPadding:CGFloat = UIDevice.current.userInterfaceIdiom == .phone ? 4 : 6
        
        //new
        public static let exteriorMargin: CGFloat = UIDevice.current.userInterfaceIdiom == .phone ? 10 : 17
//        public static let boxBottomPadding: CGFloat = UIDevice.current.userInterfaceIdiom == .phone ? 6 : 12
        public static let boxIntermittentPadding: CGFloat = UIDevice.current.userInterfaceIdiom == .phone ? 4 : 7
        
        public static let interiorMargin: CGFloat = UIDevice.current.userInterfaceIdiom == .phone ? 10 : 16
        
        public static let snippetPadding: CGFloat = UIDevice.current.userInterfaceIdiom == .phone ? 14 : 16
    }
}

public extension UtilConstants {
    public enum Keys {
        public static let activationId = "activationId"
    }
}
